### 配置客户端需要的，注册中心对外暴露的地址
eureka:
    client:
        service-url:
            defaultZone: http://localhost:11111/eureka/

#hystrix的超时时间
hystrix:
    command:
        default:
            execution:
                timeout:
                    enabled: true
                isolation:
                    thread:
                        timeoutInMilliseconds: 5000
#ribbon的超时时间
ribbon:
    ReadTimeout: 5000
    ConnectTimeout: 5000